#ifndef MY_MESSAGE_H
#define MY_MESSAGE_H

enum My_Messages{
    SHIP_PLACEMENT_MSG,
    TO_SHOOTER_HIT_MSG,
    TO_SHOOTER_MISS_MSG,
    TO_RECEIVER_HIT_MSG,
    TO_RECEIVER_MISS_MSG,
    SHOOTER_KILL_MSG,
    RECEIVER_KILL_MSG,
    SHOOT_MSG,
    READY_MSG,
    WIN_MSG,
    LOSE_MSG
};

#endif // MY_MESSAGE_H
